[package]
name = "aoc-2024-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"

[dependencies]
itertools = "0.13.0"
pathfinding = "4.11.0"
rayon = "1.10.0"
test-case = "*"
